python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-01-24 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-01-26 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-01 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-05 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-07 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-08 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-10 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-12 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-19 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-03-10 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-03-12 observer_table.csv