python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-04 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-05 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-06 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-07 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-08 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-09 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-10 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-11 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-14 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-22 observer_table.csv
