python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-04-13 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-04-28 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-05-02 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-06-29 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-07-05 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-07-21 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-08-24 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-08-26 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-08-28 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-08-31 observer_table.csv