python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-02-11 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-03-21 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-04-03 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-04-04 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-04-09 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-04-11 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-05-12 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-06-04 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-06-14 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-06-21 observer_table.csv