python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-24 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-25 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-27 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-09-30 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-10-02 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-10-16 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-10-21 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-10-23 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-10-28 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-11-02 observer_table.csv