python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-02-09 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-02-16 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-02-27 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-03-10 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-03-15 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-03-25 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-03-26 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-03-29 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-04-04 observer_table.csv