python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-07-30 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-08-10 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-08-16 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-08-20 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-08-25 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-09-22 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-09-23 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-09-26 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-09-29 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-10-06 observer_table.csv