python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-11-15 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-12-09 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-01-09 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-01-27 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-03-10 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-04-13 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-04-19 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-04-26 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-04-28 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2013-05-02 observer_table.csv