python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-11-08 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-11-17 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-11-21 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-11-22 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-11-23 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-11-28 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-12-01 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-12-05 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-12-09 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2011-12-19 observer_table.csv
python add_observer_to_data.py /Volumes/feder_data_originals/processed/2012-01-23 observer_table.csv